### ISSUE TITLE
GraphQL support not working

### ISSUE THREAD

**Issue by steida** [facebook/nuclide#1453]
`.graphqlconfig.yml`

```
projects:
  app:
    schemaPath: "schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "database/schemagenerated.graphql"
    extensions:
      prisma: database/prisma.yml
```

Is there any described the recommended graphql config file? Thank you.
